version: "3.8"

services:
  database:
    image: postgres:14.17
    container_name: system-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: system-app
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://system-db:5432/${POSTGRES_DB} #FROM .env file
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER} #FROM .env file
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD} #FROM .env file
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
volumes:
  postgres_data: