CREATE TABLE comments (
      id bigint generated by default as identity,
      text varchar not null,
      task_id int not null,
      foreign key (task_id) references tasks(id) on delete cascade
);