CREATE TABLE IF NOT EXISTS users (
     id bigint generated by default as identity,
     email varchar(255) unique not null ,
     password varchar(255) not null,
     role varchar(50) not null default 'USER'
);
